
events {}

http {

    upstream backend {
        server app:5000 weight=60;
        server nginx1:80 weight=20;
        server nginx3:80 weight=20;
    }

    map $remote_addr $safe_xff {
        default         $remote_addr;

        172.21.0.10     $http_x_forwarded_for;
        172.21.0.11     $http_x_forwarded_for;
        172.21.0.12     $http_x_forwarded_for;
    }

    server {

        listen 80;

        location / {

            proxy_set_header X-Forwarded-For
                "$safe_xff, $server_addr";

            proxy_pass http://backend;
        }
    }
}
